# ENGINES PINS
# IF YOU'RE WONDERING WHY THIS ORDER PLEASE READ :
# lynxmotion_ssc-32u_usb_user_guide.pdf

REAR_R_VERT   = 0
REAR_R_HORI   = 1
MIDDLE_R_VERT = 2
MIDDLE_R_HORI = 3
FRONT_R_VERT  = 4
FRONT_R_HORI  = 5
REAR_R_KNEE   = 6
MIDDLE_R_KNEE = 7
FRONT_R_KNEE  = 8
REAR_L_VERT   = 16
REAR_L_HORI   = 17
MIDDLE_L_VERT = 18
MIDDLE_L_HORI = 19
FRONT_L_VERT  = 20
FRONT_L_HORI  = 21
REAR_L_KNEE   = 22
MIDDLE_L_KNEE = 23
FRONT_L_KNEE  = 24

# DO NOT CHANGE THOSE ARRAYS
ENGINES_KNEE = [
    FRONT_R_KNEE, FRONT_L_KNEE,
    MIDDLE_R_KNEE, MIDDLE_L_KNEE,
    REAR_R_KNEE, REAR_L_KNEE
]

ENGINES_HORI = [
    FRONT_R_HORI, FRONT_L_HORI,
    MIDDLE_R_HORI, MIDDLE_L_HORI,
    REAR_R_HORI, REAR_L_HORI
]

ENGINE_VERT = [
    FRONT_R_VERT, FRONT_L_VERT,
    MIDDLE_R_VERT, MIDDLE_L_VERT,
    REAR_R_VERT, REAR_L_VERT
]

ENGINE_FRONT = [
    FRONT_L_VERT, FRONT_R_VERT,
    FRONT_L_HORI, FRONT_R_HORI,
    FRONT_L_KNEE, FRONT_R_KNEE
]

ENGINE_MIDDLE = [
    MIDDLE_L_VERT, MIDDLE_R_VERT,
    MIDDLE_L_HORI, MIDDLE_R_HORI,
    MIDDLE_L_KNEE, MIDDLE_R_KNEE
]

ENGINE_REAR = [
    REAR_L_VERT, REAR_R_VERT,
    REAR_L_HORI, REAR_R_HORI,
    REAR_L_KNEE, REAR_R_KNEE
]

# CONSTANTS TO IMPROVE READABILITY

# ENGINE TYPE
KNEE    = 0
HORI    = 1
REAR    = 2

# ENGINE ZONES
FRONT   = 0
MIDDLE  = 1
REAR    = 2

# MIN/MAX OF THE ENGINE
MIN     = 0
MAX     = 1

# SIDE
LEFT    = 0
RIGHT   = 1

# ENGINES MIN / MAX

#                   KNEE
# FRONT
MIN_KNEE_FRONT_LEFT      = 500
MAX_KNEE_FRONT_LEFT      = 2100
MIN_KNEE_FRONT_RIGHT     = 2500
MAX_KNEE_FRONT_RIGHT     = 900

# MIDDLE
MIN_KNEE_MIDDLE_LEFT     = 500
MAX_KNEE_MIDDLE_LEFT     = 2100
MIN_KNEE_MIDDLE_RIGHT    = 2500
MAX_KNEE_MIDDLE_RIGHT    = 900

# REAR
MIN_KNEE_REAR_LEFT       = 500
MAX_KNEE_REAR_LEFT       = 2100
MIN_KNEE_REAR_RIGHT      = 2500
MAX_KNEE_REAR_RIGHT      = 900

#                   HORI
# FRONT
MIN_HORI_FRONT_LEFT      = 2100
MAX_HORI_FRONT_LEFT      = 500
MIN_HORI_FRONT_RIGHT     = 2500
MAX_HORI_FRONT_RIGHT     = 500

# MIDDLE
MIN_HORI_MIDDLE_LEFT     = 2100
MAX_HORI_MIDDLE_LEFT     = 500
MIN_HORI_MIDDLE_RIGHT    = 2500
MAX_HORI_MIDDLE_RIGHT    = 500

# REAR
MIN_HORI_REAR_LEFT       = 2100
MAX_HORI_REAR_LEFT       = 500
MIN_HORI_REAR_RIGHT      = 2500
MAX_HORI_REAR_RIGHT      = 500

#                   VERT
# FRONT
MIN_VERT_FRONT_LEFT      = 2100
MAX_VERT_FRONT_LEFT      = 500
MIN_VERT_FRONT_RIGHT     = 1000
MAX_VERT_FRONT_RIGHT     = 2500

# MIDDLE
MIN_VERT_MIDDLE_LEFT     = 2100
MAX_VERT_MIDDLE_LEFT     = 500
MIN_VERT_MIDDLE_RIGHT    = 1000
MAX_VERT_MIDDLE_RIGHT    = 2500

# REAR
MIN_VERT_REAR_LEFT       = 2100
MAX_VERT_REAR_LEFT       = 500
MIN_VERT_REAR_RIGHT      = 1000
MAX_VERT_REAR_RIGHT      = 2500

# DO NOT CHANGE THIS
MIN_MAX_ENGINES = [
    [  # KNEE
        [[MIN_KNEE_FRONT_LEFT, MAX_KNEE_FRONT_LEFT], [      # FRONT LEFT
            MIN_KNEE_FRONT_RIGHT, MAX_KNEE_FRONT_RIGHT]],   # FRONT RIGHT
        [[MIN_KNEE_MIDDLE_LEFT, MAX_KNEE_MIDDLE_LEFT], [    # MIDDLE LEFT
            MIN_KNEE_MIDDLE_RIGHT, MAX_KNEE_MIDDLE_RIGHT]], # MIDDLE RIGHT
        [[MIN_KNEE_REAR_LEFT, MAX_KNEE_REAR_LEFT], [        # REAR LEFT
            MIN_KNEE_REAR_RIGHT, MAX_KNEE_REAR_RIGHT]],     # LEFT RIGHT
    ],
    [  # HORI
        [[MIN_HORI_FRONT_LEFT, MAX_KNEE_FRONT_LEFT], [      # FRONT LEFT
            MIN_KNEE_FRONT_RIGHT, MAX_KNEE_FRONT_RIGHT]],   # FRONT RIGHT
        [[MIN_HORI_MIDDLE_LEFT, MAX_KNEE_MIDDLE_LEFT], [    # MIDDLE LEFT
            MIN_KNEE_MIDDLE_RIGHT, MAX_KNEE_MIDDLE_RIGHT]], # MIDDLE RIGHT
        [[MIN_HORI_REAR_LEFT, MAX_KNEE_REAR_LEFT], [        # REAR LEFT
            MIN_KNEE_REAR_RIGHT, MAX_KNEE_REAR_RIGHT]],     # REAR RIGHT
    ],
    [  # VERT
        [[MIN_VERT_FRONT_LEFT, MAX_VERT_FRONT_LEFT], [      # FRONT LEFT
            MIN_VERT_FRONT_RIGHT, MAX_VERT_FRONT_RIGHT]],   # FRONT RIGHT
        [[MIN_VERT_MIDDLE_LEFT, MAX_VERT_MIDDLE_LEFT], [    # MIDDLE LEFT
            MIN_VERT_MIDDLE_RIGHT, MAX_VERT_MIDDLE_RIGHT]], # MIDDLE RIGHT
        [[MIN_VERT_REAR_LEFT, MAX_VERT_REAR_LEFT], [        # REAR LEFT
            MIN_VERT_REAR_RIGHT, MAX_VERT_REAR_RIGHT]],     # REAR RIGHT
    ]
]
''' Example :
    If you want to access max knee middle left:
    MIN_MAX_ENGINES[KNEE][MIDDLE][LEFT][MAX]
'''
